### ISSUE TITLE
ClassNotFound NamespacedKey in EnchantmentGlow

### ISSUE THREAD

**Issue by ItsFantom** [MarcinWieczorek/NovaGuilds#103]
```
[15:45:46] [Server thread/ERROR]: Error occurred while enabling NovaGuilds v40 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/NamespacedKey
	at co.marcin.novaguilds.util.EnchantmentGlow.<init>(EnchantmentGlow.java:32) ~[?:?]
	at co.marcin.novaguilds.NovaGuilds.onEnable(NovaGuilds.java:342) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d19"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]
Caused by: java.lang.ClassNotFoundException: org.bukkit.NamespacedKey
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[patched.jar:git-PaperSpigot-"4c7641d19"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-PaperSpigot-"4c7641d19"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_302]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_302]
	... 13 more
```

**Comment by MarcinWieczorek** [comment]
Send me your spigot jar via email (see my profile), should be easy to fix.

**Comment by ItsFantom** [comment]
I downloaded it from Github.

**Comment by MarcinWieczorek** [comment]
I did not ask where you downloaded it from.

**Comment by ItsFantom** [comment]
my spigot jar? what's spigot jar ;-;

**Comment by MarcinWieczorek** [comment]
The jar you use to start the server, for example `java -jar spigot.jar`

**Comment by ItsFantom** [comment]
There.

**Comment by MarcinWieczorek** [comment]
I deleted your comment. I asked to send it via email to avoid illegal distribution of Mojang copyrighted binaries.

**Comment by ItsFantom** [comment]
Done.

**Comment by ItsFantom** [comment]
Marcin can you PLEASE check inbox

**Comment by MarcinWieczorek** [comment]
I already started working on this issue, but I have very little time. Please give me some more time, I'll provide you with a fresh jar

**Comment by ItsFantom** [comment]
oh no problem sir sorry for rushing you <3 good thing is u didnt abandoned
this plugin.

**Comment by ItsFantom** [comment]
Hello marcin hows the plugin goin?

**Comment by MarcinWieczorek** [comment]
[NovaGuilds_glow.zip](https://github.com/MarcinWieczorek/NovaGuilds/files/7470365/NovaGuilds_glow.zip)

**Comment by ItsFantom** [comment]
Got it, thanks!

**Comment by MarcinWieczorek** [comment]
Please let me know if that jar works for you.

**Comment by Minecon724** [comment]
the error is still there, thrown on right clicking anything

**Comment by MarcinWieczorek** [comment]
@Minecon724 please share your server & plugin versions

**Comment by Minecon724** [comment]
This server is running [WindSpigot](https://github.com/Wind-Development/WindSpigot) Release v2.1.3 (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
NG is the file [you've sent earlier](https://github.com/MarcinWieczorek/NovaGuilds/issues/103#issuecomment-959916577)

**Comment by MarcinWieczorek** [comment]
Send me your server jar to marcin@marcin.co

**Comment by Minecon724** [comment]
sent

**Comment by MarcinWieczorek** [comment]
I have not received it.

**Comment by Minecon724** [comment]
sent again, this time a download link
