### ISSUE TITLE
Holographicdisplays error

### ISSUE THREAD

**Issue by DarkSniperXS** [MarcinWieczorek/NovaGuilds#30]
`[19:35:47 ERROR]: Error occurred while enabling NovaGuilds v25 (Is it up to date?)
java.lang.NullPointerException
        at com.gmail.filoghost.holographicdisplays.object.line.CraftItemLine.spawn(CraftItemLine.java:83) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.object.CraftHologram.refreshSingleLines(CraftHologram.java:270) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.object.CraftHologram.appendItemLine(CraftHologram.java:131) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.object.CraftHologram.appendItemLine(CraftHologram.java:1) ~[?:?]
        at co.marcin.novaguilds.manager.GuildManager.appendVaultHologram(GuildManager.java:689) ~[?:?]
        at co.marcin.novaguilds.manager.GuildManager.loadVaultHolograms(GuildManager.java:665) ~[?:?]
        at co.marcin.novaguilds.manager.GuildManager.load(GuildManager.java:240) ~[?:?]
        at co.marcin.novaguilds.NovaGuilds.onEnable(NovaGuilds.java:141) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit.jar:git-Bukkit-53fac9f]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [craftbukkit.jar:git-Bukkit-53fac9f]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit.jar:git-Bukkit-53fac9f]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:342) [craftbukkit.jar:git-Bukkit-53fac9f]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:314) [craftbukkit.jar:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:406) [craftbukkit.jar:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:370) [craftbukkit.jar:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:325) [craftbukkit.jar:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:235) [craftbukkit.jar:git-Bukkit-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:503) [craftbukkit.jar:git-Bukkit-53fac9f]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]`

**Comment by MarcinWieczorek** [comment]
What server version are you using?
What is your HolographicDisplays version?
What is your config?

**Comment by MarcinWieczorek** [comment]
http://screenshot.sh/oBKskHTzA7Pk5
This bug does not occur in build 26.
The issue might be caused by invalid/outdated HolographicDisplays plugin. It seems to have a problem creating item line (gold ingot in my case). Also the exception is thrown in HD's code. Please download latest version of that plugin.

**Comment by DarkSniperXS** [comment]
Get that screenshot look too, it shows everything is fine, the guild's vault display is up, but everytime i restart my server it crashes that and doesnt show anymore and shows its not a guild anymore.

Everything i have is updated, i am running mc 1.8.8 craftbukkit, latest version of holographicsdisplay and novaguilds.

**Comment by MarcinWieczorek** [comment]
Confirmed.
First time creating a hologam works, but after restart I get errors both for ItemStack and text lines. I'll try to fix this issue ASAP, but for now you have to set vault.hologram.enabled to false in your config.yml

Also, this seems to occur only on FLAT data system.
Thanks!
