### ISSUE TITLE
Hologram already deleted

### ISSUE THREAD

**Issue by MarcinWieczorek** [MarcinWieczorek/NovaGuilds#34]
The reason is unknown :(

```
org.bukkit.command.CommandException: Unhandled exception executing command 'nga' in plugin NovaGuilds v26
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-06ad352-4a7472d]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-06ad352-4a7472d]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-06ad352-4a7472d]
    at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-06ad352-4a7472d]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-06ad352-4a7472d]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-06ad352-4a7472d]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-06ad352-4a7472d]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-06ad352-4a7472d]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_79]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_79]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-06ad352-4a7472d]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-06ad352-4a7472d]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-06ad352-4a7472d]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-06ad352-4a7472d]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-06ad352-4a7472d]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.IllegalArgumentException: hologram already deleted
    at com.gmail.filoghost.holographicdisplays.util.Validator.isTrue(Validator.java:13) ~[?:?]
    at com.gmail.filoghost.holographicdisplays.object.CraftHologram.appendTextLine(CraftHologram.java:116) ~[?:?]
    at com.gmail.filoghost.holographicdisplays.object.CraftHologram.appendTextLine(CraftHologram.java:1) ~[?:?]
    at co.marcin.novaguilds.basic.NovaHologram.refresh(NovaHologram.java:84) ~[?:?]
    at co.marcin.novaguilds.manager.HologramManager.refreshTopHolograms(HologramManager.java:119) ~[?:?]
    at co.marcin.novaguilds.command.admin.guild.CommandAdminGuildAbandon.execute(CommandAdminGuildAbandon.java:47) ~[?:?]
    at co.marcin.novaguilds.command.admin.guild.CommandAdminGuild.execute(CommandAdminGuild.java:108) ~[?:?]
    at co.marcin.novaguilds.command.admin.CommandAdmin.onCommand(CommandAdmin.java:56) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-06ad352-4a7472d]
    ... 15 more
```

**Comment by MarcinWieczorek** [comment]
This bug doesn't seem to occur anymore
