### ISSUE TITLE
NoClassDefFoundError: com/gmail/filoghost/holographicdisplays/api/HologramsAPI

### ISSUE THREAD

**Issue by MarcinWieczorek** [MarcinWieczorek/NovaGuilds#37]
NoClassDefFoundError: com/gmail/filoghost/holographicdisplays/api/HologramsAPI

```
[20:28:36 ERROR]: Error occurred while disabling NovaGuilds v28 (Is it up to date?)
java.lang.NoClassDefFoundError: com/gmail/filoghost/holographicdisplays/api/HologramsAPI
    at co.marcin.novaguilds.NovaGuilds.onDisable(NovaGuilds.java:291) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:318) ~[PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
    at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:356) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
    at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:431) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
    at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:424) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.disablePlugins(CraftServer.java:412) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
    at net.minecraft.server.v1_7_R4.MinecraftServer.stop(MinecraftServer.java:387) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:584) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
Caused by: java.lang.ClassNotFoundException: com.gmail.filoghost.holographicdisplays.api.HologramsAPI
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_66]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_66]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_66]
    ... 9 more

```

Similar thing occurs for BarAPI. Seems that these plugins are being disabled before NG.

**Comment by MarcinWieczorek** [comment]
HologramsAPI class doesn't exist in 1.7 version of HolographicDisplays.
