### ISSUE TITLE
Tablist..

### ISSUE THREAD

**Issue by kachekos** [MarcinWieczorek/NovaGuilds#52]
I have Colored Tablist on the my server..(Plugin ColoredTags).
I turned off all tab options to falsein the cofig.yml,
but when someone do /join GUILD or /create GUILD, my Colored Tablist became WHITE..
And only restart of the server can help.. Hope it will be able to fix it

**Comment by MarcinWieczorek** [comment]
You turned off what and in wchich config? 
Please reply attaching both your configs (tab plugin and NG)
That issue is a bit weird, such problem should occur at all. Although I will look into this

**Comment by MarcinWieczorek** [comment]
Should not\* typo.

**Comment by kachekos** [comment]
I think that it is Tablist scoreboard conflict of Colored Tags and NovaGuilds..
My TabApi in NG turned off..
tabapi:
 colortags: false
 rankprefix: false

**Comment by MarcinWieczorek** [comment]
Then it should not crash the tab at all!
I'm gonna try to bug it as soon as I arrive home. Actually I've got an idea...

**Comment by kachekos** [comment]
Oh.. I think i found a problem.. If i do NG tabapi to false its still working, this why conflict near Colored Tags and NG..

**Comment by kachekos** [comment]
And some issue with /nga reload 
[15:50:00] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'nga' in plugin NovaGuilds v26
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server8.jar:git-Spigot-f928e7a-e91aed8]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server8.jar:git-Spigot-f928e7a-e91aed8]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) ~[server8.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [server8.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [server8.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [server8.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [server8.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server8.jar:git-Spigot-f928e7a-e91aed8]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [server8.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [server8.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [server8.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [server8.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [server8.jar:git-Spigot-f928e7a-e91aed8]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
    at co.marcin.novaguilds.manager.DatabaseManager.mysqlReload(DatabaseManager.java:145) ~[?:?]
    at co.marcin.novaguilds.manager.RegionManager.load(RegionManager.java:98) ~[?:?]
    at co.marcin.novaguilds.command.admin.CommandAdminReload.execute(CommandAdminReload.java:72) ~[?:?]
    at co.marcin.novaguilds.command.admin.CommandAdmin.onCommand(CommandAdmin.java:72) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server8.jar:git-Spigot-f928e7a-e91aed8]
    ... 15 more

**Comment by MarcinWieczorek** [comment]
So is the problem with tab fixed?

Please tell me what plugin version are you using?
Also you should not use /nga reload, just because it can be not 100% working and buggy, like Bukkit's /reload command is. ;)

**Comment by kachekos** [comment]
Problem didnt fix... I said that  after changing tabapi from true to false, NG still working at tab... I tried to use latest dev build and stable but there is no difference at tab menu..
About reload it ok :smile:

**Comment by kachekos** [comment]
Before and after http://imgur.com/a/nLook

**Comment by MarcinWieczorek** [comment]
Stay with the latest dev version.
