### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [MarcinWieczorek/NovaGuilds#53]
`ode (Text):
[16:22:38] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to NovaGuilds v31
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[serwer.jar:git-PaperSpigot-"ee63dbe"]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[serwer.jar:git-PaperSpigot-"ee63dbe"]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[serwer.jar:git-PaperSpigot-"ee63dbe"]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [serwer.jar:git-PaperSpigot-"ee63dbe"]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [serwer.jar:git-PaperSpigot-"ee63dbe"]
    at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:314) [serwer.jar:git-PaperSpigot-"ee63dbe"]
    at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:173) [serwer.jar:git-PaperSpigot-"ee63dbe"]
    at protocolsupport.protocol.transformer.handlers.AbstractLoginListener.b(AbstractLoginListener.java:145) [ProtocolSupport.jar:?]
    at protocolsupport.protocol.transformer.handlers.AbstractLoginListener.c(AbstractLoginListener.java:91) [ProtocolSupport.jar:?]
    at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [serwer.jar:git-PaperSpigot-"ee63dbe"]
    at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [serwer.jar:git-PaperSpigot-"ee63dbe"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:873) [serwer.jar:git-PaperSpigot-"ee63dbe"]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [serwer.jar:git-PaperSpigot-"ee63dbe"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [serwer.jar:git-PaperSpigot-"ee63dbe"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [serwer.jar:git-PaperSpigot-"ee63dbe"]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.IllegalArgumentException: Team name 'ng_QiiQii' is already in use
    at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[serwer.jar:git-PaperSpigot-"ee63dbe"]
    at org.bukkit.craftbukkit.v1_8_R3.scoreboard.CraftScoreboard.registerNewTeam(CraftScoreboard.java:140) ~[serwer.jar:git-PaperSpigot-"ee63dbe"]
    at co.marcin.novaguilds.util.TagUtils.updatePrefix(TagUtils.java:81) ~[?:?]
    at co.marcin.novaguilds.listener.LoginListener.onPlayerJoin(LoginListener.java:79) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[serwer.jar:git-PaperSpigot-"ee63dbe"]
    ... 15 more`

**Comment by MarcinWieczorek** [comment]
Please provide more information. What must I do to reproduce this error?
What are your online players' names? It seems that there are two players `QiiQii`

**Comment by ghost** [comment]
a nie możemy po polsku pisać '_'

proszę,
pliki serwerowe
`https://drive.google.com/file/d/0B4sNCwuKX5m8eXNMalR4ckNaZ1k/view?usp=sharing`
- 
  skan
  `https://www.virustotal.com/pl/file/53b0509e698b6e28e8e21b51024ef1974a08510e577e6607e1847af87e231d68/analysis/1456008698/`

testowałem w środowisku windows 8.1 x64, java 8 x64 (najnowsza raczej)

**Comment by MarcinWieczorek** [comment]
Z fusów miałem wywróżyć że Polakiem jesteś skoro na spigocie pisałeś?
To nie mpc, tutaj się skanów nie wrzuca. Na grzyba mi Twoje pliki serwerowe? Nic z nich nie wyczytam.

Chociaż może...

``` datastorage:
 primary: sqlite
 secondary: sqlite
```

Wiesz że to Ci przestawi ustawienia na domyślną wartość (mysql i flat)? Masz to napisane wołami przy rozruchu. To jednak nie jest przyczyną problemu. Twój config jest bardzo stary, powinieneś go zresetować.

**Comment by ghost** [comment]
a bo kiedyś już ze sobą na spigotmc pisaliśmy i myślałem że mnie pamiętasz, ale jak widać kłębkiem świata nie jestem.

właśnie zastanawiałem się oco z tym chodzi

 primary: sqlite
 secondary: sqlite

odstaje to od standardów, inne pluginy mają tylko mysql i się wybiera true lub false

dałem Ci pliki serwerowe bo pomyślałem że tak będzie najszybciej, gdybym ci próbował przedstawić sytuacje opisując krok po kroku, to bym autorem książki został : P

inne pluginy mają automatyczny update/import configu ze starszej wersji pod nową.
ale to tylko taka sugestia.

no i podpiąłem pod bazę mysql wygenerowaną przez starszą wersje.

`[01:04:45] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to NovaGuilds v31
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[serwer.jar:git-PaperSpigot-"ee63dbe"]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[serwer.jar:git-PaperSpigot-"ee63dbe"]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[serwer.jar:git-PaperSpigot-"ee63dbe"]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [serwer.jar:git-PaperSpigot-"ee63dbe"]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [serwer.jar:git-PaperSpigot-"ee63dbe"]
    at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:314) [serwer.jar:git-PaperSpigot-"ee63dbe"]
    at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:173) [serwer.jar:git-PaperSpigot-"ee63dbe"]
    at protocolsupport.protocol.transformer.handlers.AbstractLoginListener.b(AbstractLoginListener.java:145) [ProtocolSupport.jar:?]
    at protocolsupport.protocol.transformer.handlers.AbstractLoginListener.c(AbstractLoginListener.java:91) [ProtocolSupport.jar:?]
    at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [serwer.jar:git-PaperSpigot-"ee63dbe"]
    at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [serwer.jar:git-PaperSpigot-"ee63dbe"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:873) [serwer.jar:git-PaperSpigot-"ee63dbe"]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [serwer.jar:git-PaperSpigot-"ee63dbe"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [serwer.jar:git-PaperSpigot-"ee63dbe"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [serwer.jar:git-PaperSpigot-"ee63dbe"]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.IllegalArgumentException: Team name 'ng_QiiQii' is already in use
    at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[serwer.jar:git-PaperSpigot-"ee63dbe"]
    at org.bukkit.craftbukkit.v1_8_R3.scoreboard.CraftScoreboard.registerNewTeam(CraftScoreboard.java:140) ~[serwer.jar:git-PaperSpigot-"ee63dbe"]
    at co.marcin.novaguilds.util.TagUtils.updatePrefix(TagUtils.java:81) ~[?:?]
    at co.marcin.novaguilds.listener.LoginListener.onPlayerJoin(LoginListener.java:79) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[serwer.jar:git-PaperSpigot-"ee63dbe"]
    ... 15 more`

teraz tagi nie działają.

**Comment by MarcinWieczorek** [comment]
Nie no przegiąłeś trochę, weź daj to na pastebin czy coś.

To, że inne pluginy mają mysql true/false, to nie znaczy że mój ma nie mieć awaryjnego trybu zapisu danych na wypadek gdyby nie udało się połączyć z głównym... A ponieważ są trzy opcje do wyboru to trzeba wpisać. Więcej bym z logów wyczytał niż ze spigot.jar. Config to sobie zdążyłem podpatrzeć.

Aktualizacja configu wiąże się z usunięciem komentarzy. Jak chcesz potem coś zmienić to jak to się mówi `bądź mądry - pisz wiersze`. Nie ogarniesz.

Natomiast baza danych aktualizuje się sama, ale tylko do przodu :P
Jeśli w tym pluginie czegoś nie ma, to znaczy że jest na to dobry powód.

**Comment by MarcinWieczorek** [comment]
Czy Ty właśnie edytowałeś tamten komentarz?
Tagi nie działają czyli co? Z fusów wróżymy? logi logi

**Comment by mat41997** [comment]
nie.

**Comment by mat41997** [comment]
już kopiuje

**Comment by ghost** [comment]
proszę,
`http://hastebin.com/cozodofoce.profile`

tagi nie działają po aktualizacji z wersji ng26 do wersji ng31

jeszcze przedtem go edytowałem, nie wiem po co wkleiłem config, na dodatek źle go sformatowało noi i wyszło że przegiąłem.

**Comment by MarcinWieczorek** [comment]
Bo w configu jest coś od tych tagów. Może jest wyłączone domyślnie. To może być tagapi.enabled, ale zaraz zobaczę w kodzie. Mowa o tagach w tabie, no bo ogólnie to nie ma się co popsuć. Ten błąd co tam masz jest dość dziwny. Zobacz czy Ci się nie zdublowali gracze w bazie

**Comment by ghost** [comment]
config
`http://hastebin.com/acezupazaj.rb`

moja aktualna plugin lista
`Plugins (42): WorldEdit, Skript, BarAPI, LogBlock, PluginManagerReloaded, NametagEdit, CustomRecipes, ActionHealth, ProtocolLib, WorldGuard, LibsDisguises, NoCheatPlus, SuperTrails, Shopkeepers, WildSkript, PermissionsEx, JaszczuStone, DiscoArmor, AntiJoinBot, hlRandom, StaffChat, Tablist, Vault, ColoredAnvils, ProtocolSupport, SilkChests, MassiveCore, MyPet, CombatTagPlus, Essentials, SexyMotd, ChangeSkin, ScoreboardStats, CreativeGates, Trading, HolographicDisplays, EssentialsChat, EssentialsSpawn, Timeismoney, NovaGuilds, AuthMe, TouchscreenHolograms`

możliwe że to przez plugin ProtocolSupport

**Comment by ghost** [comment]
a i czy mógłbyś podzielić listę która wyskakuje po wpisaniu polecenia /g na dwie części? bo w czacie się nie mieści, poza tym gdy gracze szybko piszą na czacie, to ona ucieka szybko i nie można przeczytać.

do tagów na tabie jak i na tagu używam pluginu NametagEdit.

**Comment by MarcinWieczorek** [comment]
w sensie ze stronami?

**Comment by ghost** [comment]
tak

**Comment by MarcinWieczorek** [comment]
ok, kiedyś się zrobi. Sprawdzałeś to co mówiłem? Bo nie wiem nic na temat tego błędu

**Comment by ghost** [comment]
a jakby je jeszcze kliknąć można było, to już by było super : ) wgl. jakby każde polecenie z listy można było kliknąć i automatycznie wpisało by się w linijkę czatu.

**Comment by ghost** [comment]
a co miałem sprawdzić? XD
podałem swój config. aktualny, ten nowy.

o ten
http://hastebin.com/acezupazaj.rb

**Comment by ghost** [comment]
o mam
http://hastebin.com/qilewajeru.coffee

**Comment by ghost** [comment]
a teraz mi jeszcze coś takiego wyskoczyło
http://hastebin.com/jiziqujazi.sm
nwm, może to wina hostingu.

**Comment by MarcinWieczorek** [comment]
ok, kiedyś się zrobi. Sprawdzałeś to co mówiłem? Bo nie wiem nic na temat tego błędu

**Comment by ghost** [comment]
proszę,
http://hastebin.com/iwudiriyip.vala

**Comment by ghost** [comment]
zauważyłem że ten error który ci podałem nie wyskakuje zawsze, tylko pojawia się wtedy kiedy wbije graczy który wbił kiedy była jeszcze stara wersja ng26. gracze którzy wbili po raz pierwszy kiedy był już ng31 nie mają tego problemu. pewnie portowanie bazy danych mysql źle działa.
ten error
http://hastebin.com/jicukacoyi.profile

a co do tagów to mimo iż w configu permissionsex dałem 
http://hastebin.com/rizimenani.sm

to się nie wyświetla gdy admin ma op'a, czy jakoś tak.

zwykłym graczą działa, widać tag gildi na tabliście i na czacie.
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

a czy mógłbyś dodać by można było zmienić kolor graczy na tabliście, graczy nie będących w żadnej gildii?
i czy mógłbyś dodać aby pod nickiem nad głową gracza wyświetlała się ilość punktów gracza tak jak w funnyguilds?

**Comment by MarcinWieczorek** [comment]
Z tego co widzę to ten błąd nie występuje gdy QiiQii wejdzie, tylko ktokolwiek. Może się coś zbugowało w spigocie, miałem już taką sytuację. Pomogło usunięcie scoreboardów z folderu ze światem.

Kolory nicków w tabie będą jak najbardziej wykonalne, może nawet w buildzie 32. Dodam osobny szablon tagów do taba, więc wystarczy zamiast tagu dać sam kolor.

No opa to nie dawaj, bo może się gryźć. Gwiazdka i -novaguilds.chat.notag powinno działać. 

To co zauważyłeś ze starymi i nowymi graczami to wreszcie coś co mi pozwoli efektywnie szukać błedu. Szczerze mówiąc to nie mam pojęcia co to może być, ale już wiadomo więcej ^^
We wszystkich logach jeden i ten sam błąd.

**Comment by MarcinWieczorek** [comment]
`/scoreboard teams list`
Wywal te zbugowane `ng_QiiQii`
