### ISSUE TITLE
Problem na wersji #34

### ISSUE THREAD

**Issue by RafalKedziora** [MarcinWieczorek/NovaGuilds#60]
Witaj. Przy okazji wypuszczenia wersji #34 znalazłem taki błąd
Silnik: Spigot 1.7-1.8

```
[12:30:02 INFO]: AkuaFite wywołał komendę: /zaloz MOC MOCARSTWO
save-all
[12:30:02 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'create' in plugin NovaGuilds v34
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
Caused by: java.lang.NullPointerException
at co.marcin.novaguilds.manager.GuildManager.createHomeFloor(GuildManager.java:244) ~[?:?]
at co.marcin.novaguilds.command.guild.CommandGuildCreate.execute(CommandGuildCreate.java:215) ~[?:?]
at co.marcin.novaguilds.manager.CommandManager.execute(CommandManager.java:327) ~[?:?]
at co.marcin.novaguilds.enums.Command.execute(Command.java:182) ~[?:?]
at co.marcin.novaguilds.command.guild.CommandGuildCreate.onCommand(CommandGuildCreate.java:64) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
... 13 more
```

**Comment by MarcinWieczorek** [comment]
Naprawiony w 949c697d08f1c3c58bb1f0aabedddacb095af612 a łatka wydana przedwczoraj.
http://repo.novaguilds.pl/co/marcin/novaguilds/34/
