### ISSUE TITLE
Error while /g items

### ISSUE THREAD

**Issue by troley12** [MarcinWieczorek/NovaGuilds#71]
It's a error on Spigot 1.8.8:

``` plain
[18:34:36 INFO]: Kuuuba issued server command: /g items
[18:34:36 ERROR]: [NovaGuilds]
[18:34:36 ERROR]: [NovaGuilds] [NovaGuilds] Severe error: CommandException
[18:34:36 ERROR]: [NovaGuilds]
[18:34:36 ERROR]: [NovaGuilds] Server Information:
[18:34:36 ERROR]: [NovaGuilds]   NovaGuilds: #38 (6e1c09a)
[18:34:36 ERROR]: [NovaGuilds]   Storage Type: MYSQL
[18:34:36 ERROR]: [NovaGuilds]   Bukkit: 1.8.8-R0.1-SNAPSHOT
[18:34:36 ERROR]: [NovaGuilds]   Java: 1.8.0_101
[18:34:36 ERROR]: [NovaGuilds]   Thread: Thread[Server thread,5,main]
[18:34:36 ERROR]: [NovaGuilds]   Running CraftBukkit: false
[18:34:36 ERROR]: [NovaGuilds]   Exception Message:
[18:34:36 ERROR]: [NovaGuilds]    Unhandled exception executing command 'GUILD_REQUIREDITEMS' in plugin NovaGuilds
[18:34:36 ERROR]: [NovaGuilds]
[18:34:36 ERROR]: [NovaGuilds] Stack trace:
[18:34:36 ERROR]: [NovaGuilds]  at co.marcin.novaguilds.manager.CommandManager.execute(CommandManager.java:277)
[18:34:36 ERROR]: [NovaGuilds]  at co.marcin.novaguilds.enums.Command.execute(Command.java:267)
[18:34:36 ERROR]: [NovaGuilds]  at co.marcin.novaguilds.command.guild.CommandGuild.execute(CommandGuild.java:86)
[18:34:36 ERROR]: [NovaGuilds]  at co.marcin.novaguilds.manager.CommandManager.execute(CommandManager.java:274)
[18:34:36 ERROR]: [NovaGuilds]  at co.marcin.novaguilds.enums.Command.execute(Command.java:267)
[18:34:36 ERROR]: [NovaGuilds]  at co.marcin.novaguilds.command.guild.CommandGuild.onCommand(CommandGuild.java:126)
[18:34:36 ERROR]: [NovaGuilds]  at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[18:34:36 ERROR]: [NovaGuilds]  at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[18:34:36 ERROR]: [NovaGuilds]  at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[18:34:36 ERROR]: [NovaGuilds]  at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[18:34:36 ERROR]: [NovaGuilds]  at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[18:34:36 ERROR]: [NovaGuilds]  at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[18:34:36 ERROR]: [NovaGuilds]  at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[18:34:36 ERROR]: [NovaGuilds]  at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[18:34:36 ERROR]: [NovaGuilds]  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:34:36 ERROR]: [NovaGuilds]  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:34:36 ERROR]: [NovaGuilds]  at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[18:34:36 ERROR]: [NovaGuilds]  at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[18:34:36 ERROR]: [NovaGuilds]  at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[18:34:36 ERROR]: [NovaGuilds]  at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[18:34:36 ERROR]: [NovaGuilds]  at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[18:34:36 ERROR]: [NovaGuilds]  at java.lang.Thread.run(Thread.java:745)
[18:34:36 ERROR]: [NovaGuilds]
[18:34:36 ERROR]: [NovaGuilds] Caused by: java.lang.ArrayIndexOutOfBoundsException
[18:34:36 ERROR]: [NovaGuilds]   -1
[18:34:36 ERROR]: [NovaGuilds]  at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventoryCustom$MinecraftInventory.getItem(CraftInventoryCustom.java:72)
[18:34:36 ERROR]: [NovaGuilds]  at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventory.getItem(CraftInventory.java:47)
[18:34:36 ERROR]: [NovaGuilds]  at co.marcin.novaguilds.util.ChestGUIUtils.addBackItem(ChestGUIUtils.java:80)
[18:34:36 ERROR]: [NovaGuilds]  at co.marcin.novaguilds.util.ChestGUIUtils.openGUIInventory(ChestGUIUtils.java:54)
[18:34:36 ERROR]: [NovaGuilds]  at co.marcin.novaguilds.impl.util.AbstractGUIInventory.open(AbstractGUIInventory.java:62)
[18:34:36 ERROR]: [NovaGuilds]  at co.marcin.novaguilds.command.guild.CommandGuildRequiredItems.execute(CommandGuildRequiredItems.java:38)
[18:34:36 ERROR]: [NovaGuilds]  at co.marcin.novaguilds.manager.CommandManager.execute(CommandManager.java:274)
[18:34:36 ERROR]: [NovaGuilds]  at co.marcin.novaguilds.enums.Command.execute(Command.java:267)
[18:34:36 ERROR]: [NovaGuilds]  at co.marcin.novaguilds.command.guild.CommandGuild.execute(CommandGuild.java:86)
[18:34:36 ERROR]: [NovaGuilds]  at co.marcin.novaguilds.manager.CommandManager.execute(CommandManager.java:274)
[18:34:36 ERROR]: [NovaGuilds]  at co.marcin.novaguilds.enums.Command.execute(Command.java:267)
[18:34:36 ERROR]: [NovaGuilds]  at co.marcin.novaguilds.command.guild.CommandGuild.onCommand(CommandGuild.java:126)
[18:34:36 ERROR]: [NovaGuilds]  at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[18:34:36 ERROR]: [NovaGuilds]  at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[18:34:36 ERROR]: [NovaGuilds]  at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[18:34:36 ERROR]: [NovaGuilds]  at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[18:34:36 ERROR]: [NovaGuilds]  at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[18:34:36 ERROR]: [NovaGuilds]  at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[18:34:36 ERROR]: [NovaGuilds]  at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[18:34:36 ERROR]: [NovaGuilds]  at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[18:34:36 ERROR]: [NovaGuilds]  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:34:36 ERROR]: [NovaGuilds]  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:34:36 ERROR]: [NovaGuilds]  at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[18:34:36 ERROR]: [NovaGuilds]  at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[18:34:36 ERROR]: [NovaGuilds]  at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[18:34:36 ERROR]: [NovaGuilds]  at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[18:34:36 ERROR]: [NovaGuilds]  at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[18:34:36 ERROR]: [NovaGuilds]  at java.lang.Thread.run(Thread.java:745)
[18:34:36 ERROR]: [NovaGuilds]
[18:34:36 ERROR]: [NovaGuilds] End of Error.
[18:34:36 ERROR]: [NovaGuilds]
```

Config `http://wklej.org/id/2824222/`

**Comment by jakubgross** [comment]
Config - [http://wklej.org/id/2824222/](url)

**Comment by MarcinWieczorek** [comment]
You can apply this patch to the current release/38 branch and compile the plugin. This will be committed soon.

``` patch
@@ -43,7 +43,7 @@ public class ChestGUIUtils {
     * @return suitable inventory size
     */
    public static int getChestSize(int count) {
-       return (count / 9) * 9 + (count % 9 == 0 ? 0 : 9);
+       return count == 0 ? 9 : (count / 9) * 9 + (count % 9 == 0 ? 0 : 9);
    }

    /**

```
