### ISSUE TITLE
Chat bug and plugin

### ISSUE THREAD

**Issue by KopytkoTV** [MarcinWieczorek/NovaGuilds#80]
hi im install you plugin .but is work and im dont now why is bugged im not can  write in chat 
config
in pw 

eror log  when im create guild creating guild 

```plain
[23:03:36 ERROR]: [NovaGuilds] Exception Message: 
[23:03:36 ERROR]: [NovaGuilds]  Unhandled exception executing command 'GUILD_CREATE' in plugin NovaGuilds
[23:03:36 ERROR]: [NovaGuilds]   at co.marcin.novaguilds.manager.CommandManager.execute(CommandManager.java:145)
[23:03:36 ERROR]: [NovaGuilds]   at co.marcin.novaguilds.impl.basic.CommandWrapperImpl.execute(CommandWrapperImpl.java:114)
[23:03:36 ERROR]: [NovaGuilds]   at co.marcin.novaguilds.manager.CommandManager$GenericExecutor.onCommand(CommandManager.java:169)
[23:03:36 ERROR]: [NovaGuilds]   at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[23:03:36 ERROR]: [NovaGuilds]   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[23:03:36 ERROR]: [NovaGuilds]   at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
[23:03:36 ERROR]: [NovaGuilds]   at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133)
[23:03:36 ERROR]: [NovaGuilds]   at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968)
[23:03:36 ERROR]: [NovaGuilds]   at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[23:03:36 ERROR]: [NovaGuilds]   at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[23:03:36 ERROR]: [NovaGuilds]   at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[23:03:36 ERROR]: [NovaGuilds]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[23:03:36 ERROR]: [NovaGuilds]   at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[23:03:36 ERROR]: [NovaGuilds]   at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
[23:03:36 ERROR]: [NovaGuilds]   at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710)
[23:03:36 ERROR]: [NovaGuilds]   at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
[23:03:36 ERROR]: [NovaGuilds]   at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
[23:03:36 ERROR]: [NovaGuilds]   at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
[23:03:36 ERROR]: [NovaGuilds]   at java.lang.Thread.run(Thread.java:745)
[23:03:36 ERROR]: [NovaGuilds] 
[23:03:36 ERROR]: [NovaGuilds] Caused by: java.lang.NullPointerException
[23:03:36 ERROR]: [NovaGuilds]  null
[23:03:36 ERROR]: [NovaGuilds]   at co.marcin.novaguilds.command.guild.CommandGuildCreate.execute(CommandGuildCreate.java:230)
[23:03:36 ERROR]: [NovaGuilds]   at co.marcin.novaguilds.manager.CommandManager.execute(CommandManager.java:142)
[23:03:36 ERROR]: [NovaGuilds]   at co.marcin.novaguilds.impl.basic.CommandWrapperImpl.execute(CommandWrapperImpl.java:114)
[23:03:36 ERROR]: [NovaGuilds]   at co.marcin.novaguilds.manager.CommandManager$GenericExecutor.onCommand(CommandManager.java:169)
[23:03:36 ERROR]: [NovaGuilds]   at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[23:03:36 ERROR]: [NovaGuilds]   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[23:03:36 ERROR]: [NovaGuilds]   at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
[23:03:36 ERROR]: [NovaGuilds]   at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133)
[23:03:36 ERROR]: [NovaGuilds]   at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968)
[23:03:36 ERROR]: [NovaGuilds]   at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[23:03:36 ERROR]: [NovaGuilds]   at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[23:03:36 ERROR]: [NovaGuilds]   at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[23:03:36 ERROR]: [NovaGuilds]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[23:03:36 ERROR]: [NovaGuilds]   at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[23:03:36 ERROR]: [NovaGuilds]   at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
[23:03:36 ERROR]: [NovaGuilds]   at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710)
[23:03:36 ERROR]: [NovaGuilds]   at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
[23:03:36 ERROR]: [NovaGuilds]   at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
[23:03:36 ERROR]: [NovaGuilds]   at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
[23:03:36 ERROR]: [NovaGuilds]   at java.lang.Thread.run(Thread.java:745)
[23:03:36 ERROR]: [NovaGuilds] 
[23:03:36 ERROR]: [NovaGuilds] End of Error.
[23:03:36 ERROR]: [NovaGuilds] 

```

**Comment by MarcinWieczorek** [comment]
This: `Please send this whole message to the author`
and this: `End of Error.` exist for a reason.
Please paste a complete server log.
I appreciate the effort you've put into your description but please hide your database password.

**Comment by KopytkoTV** [comment]
https://paste.ofcode.org/gfn4cgzp2pcT5U8VskneWt here is

**Comment by KopytkoTV** [comment]
bug is end  serwer is weak    low ram im have unilimited ram and 
mistake disappeared cls

**Comment by MarcinWieczorek** [comment]
Yeah my guess was that you ran out of ram. But with 5 players? How much did you allocate, 8MB?
I could not reproduce your issue.
