### ISSUE TITLE
Database configuration

### ISSUE THREAD

**Issue by insertt** [MarcinWieczorek/NovaGuilds#82]
If you set primary datastorage to flat, and then secondary flat too (i didnt test others), plugin is getting mad and it's trying to connect to mysql database and throwing many exceptions:

```
[15:56:25] [Server thread/INFO]: [NovaGuilds][StorageConnector] Connecting to MYSQL storage (attempt: 1)
[15:56:25] [Server thread/INFO]: [NovaGuilds][StorageConnector] java.lang.IllegalArgumentException
[15:56:25] [Server thread/INFO]: [NovaGuilds][StorageConnector] MySQL credentials not specified in the config. Switching to secondary storage.
[15:56:25] [Server thread/INFO]: [NovaGuilds][StorageConnector] Connecting to MYSQL storage (attempt: 1)
[15:56:25] [Server thread/INFO]: [NovaGuilds][StorageConnector] java.lang.IllegalArgumentException
[15:56:25] [Server thread/INFO]: [NovaGuilds][StorageConnector] MySQL credentials not specified in the config. Switching to secondary storage.
[15:56:25] [Server thread/INFO]: [NovaGuilds][StorageConnector] Connecting to MYSQL storage (attempt: 1)
[15:56:25] [Server thread/INFO]: [NovaGuilds][StorageConnector] java.lang.IllegalArgumentException
[15:56:25] [Server thread/INFO]: [NovaGuilds][StorageConnector] MySQL credentials not specified in the config. Switching to secondary storage.
[15:56:25] [Server thread/INFO]: [NovaGuilds][StorageConnector] Connecting to MYSQL storage (attempt: 1)
[15:56:25] [Server thread/INFO]: [NovaGuilds][StorageConnector] java.lang.IllegalArgumentException
[15:56:25] [Server thread/INFO]: [NovaGuilds][StorageConnector] MySQL credentials not specified in the config. Switching to secondary storage.
[15:56:25] [Server thread/INFO]: [NovaGuilds][StorageConnector] Connecting to MYSQL storage (attempt: 1)
[15:56:25] [Server thread/INFO]: [NovaGuilds][StorageConnector] java.lang.IllegalArgumentException
[15:56:25] [Server thread/INFO]: [NovaGuilds][StorageConnector] MySQL credentials not specified in the config. Switching to secondary storage.
[15:56:25] [Server thread/INFO]: [NovaGuilds][StorageConnector] Connecting to MYSQL storage (attempt: 1)
[15:56:25] [Server thread/INFO]: [NovaGuilds][StorageConnector] java.lang.IllegalArgumentException
[15:56:25] [Server thread/INFO]: [NovaGuilds][StorageConnector] MySQL credentials not specified in the config. Switching to secondary storage.
[15:56:25] [Server thread/INFO]: [NovaGuilds][StorageConnector] Connecting to MYSQL storage (attempt: 1)
[15:56:25] [Server thread/INFO]: [NovaGuilds][StorageConnector] java.lang.IllegalArgumentException
[15:56:25] [Server thread/INFO]: [NovaGuilds][StorageConnector] MySQL credentials not specified in the config. Switching to secondary storage.
[15:56:25] [Server thread/INFO]: [NovaGuilds][StorageConnector] Connecting to MYSQL storage (attempt: 1)
[15:56:25] [Server thread/INFO]: [NovaGuilds][StorageConnector] java.lang.IllegalArgumentException
[15:56:25] [Server thread/INFO]: [NovaGuilds][StorageConnector] MySQL credentials not specified in the config. Switching to secondary storage.
```

and over and over spamming console until StackOverflowError got thrown out

```
[15:56:41] [Server thread/ERROR]: Error occurred while enabling NovaGuilds v39 (Is it up to date?)
java.lang.StackOverflowError
	at java.util.GregorianCalendar.computeFields(Unknown Source) ~[?:1.8.0_66]
	at java.util.Calendar.setTimeInMillis(Unknown Source) ~[?:1.8.0_66]
	at java.util.Calendar.setTime(Unknown Source) ~[?:1.8.0_66]
	at java.text.SimpleDateFormat.format(Unknown Source) ~[?:1.8.0_66]
	at java.text.SimpleDateFormat.format(Unknown Source) ~[?:1.8.0_66]
	at java.text.DateFormat.format(Unknown Source) ~[?:1.8.0_66]
	at java.text.Format.format(Unknown Source) ~[?:1.8.0_66]
	at org.apache.logging.log4j.core.pattern.DatePatternConverter.format(DatePatternConverter.java:166) ~[patched_1.11.2.jar:git-Paper-1083]
	at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:36) ~[patched_1.11.2.jar:git-Paper-1083]
	at org.apache.logging.log4j.core.layout.PatternLayout.toSerializable(PatternLayout.java:167) ~[patched_1.11.2.jar:git-Paper-1083]
	at org.apache.logging.log4j.core.layout.PatternLayout.toSerializable(PatternLayout.java:52) ~[patched_1.11.2.jar:git-Paper-1083]
	at org.apache.logging.log4j.core.layout.AbstractStringLayout.toByteArray(AbstractStringLayout.java:45) ~[patched_1.11.2.jar:git-Paper-1083]
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:111) ~[patched_1.11.2.jar:git-Paper-1083]
	at org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender.append(RollingRandomAccessFileAppender.java:96) ~[patched_1.11.2.jar:git-Paper-1083]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99) ~[patched_1.11.2.jar:git-Paper-1083]
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:425) ~[patched_1.11.2.jar:git-Paper-1083]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406) ~[patched_1.11.2.jar:git-Paper-1083]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367) ~[patched_1.11.2.jar:git-Paper-1083]
	at org.apache.logging.log4j.core.Logger.log(Logger.java:110) ~[patched_1.11.2.jar:git-Paper-1083]
	at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1039) ~[patched_1.11.2.jar:git-Paper-1083]
	at org.bukkit.craftbukkit.v1_11_R1.util.ForwardLogHandler.publish(ForwardLogHandler.java:37) ~[patched_1.11.2.jar:git-Paper-1083]
	at java.util.logging.Logger.log(Unknown Source) ~[?:1.8.0_66]
	at java.util.logging.Logger.doLog(Unknown Source) ~[?:1.8.0_66]
	at java.util.logging.Logger.log(Unknown Source) ~[?:1.8.0_66]
	at java.util.logging.Logger.info(Unknown Source) ~[?:1.8.0_66]
	at co.marcin.novaguilds.util.LoggerUtils.info(LoggerUtils.java:93) ~[?:?]
	at co.marcin.novaguilds.util.LoggerUtils.info(LoggerUtils.java:79) ~[?:?]
	at co.marcin.novaguilds.impl.storage.StorageConnector.connect(StorageConnector.java:100) ~[?:?]
	at co.marcin.novaguilds.impl.storage.StorageConnector.handle(StorageConnector.java:65) ~[?:?]
	at co.marcin.novaguilds.impl.storage.StorageConnector.handle(StorageConnector.java:90) ~[?:?]
	at co.marcin.novaguilds.impl.storage.StorageConnector.handle(StorageConnector.java:90) ~[?:?]
```

I think there should be a anti-idiot check when someone set these variables to the same data storage

**Comment by MarcinWieczorek** [comment]
There is one indeed. I could never reproduce this error but I am aware of it. Please use new snapshots. Make sure not to use /reload command. Thanks for reporting the issue.

**Comment by insertt** [comment]
I've tested this out - the version from dev.bukkit (39) is generating these errors, latest snapshot doesn't, so i think it's solved :D

**Comment by MarcinWieczorek** [comment]
I think I might have solved it since 39.
