### ISSUE TITLE
t

### ISSUE THREAD

**Issue by aztkk** [MarcinWieczorek/NovaGuilds#84]
```[16:39:59 ERROR]: [NovaGuilds]
[16:39:59 ERROR]: [NovaGuilds] Exception Message:
[16:39:59 ERROR]: [NovaGuilds]Cannot set already-set enchantment
[16:39:59 ERROR]: [NovaGuilds]at org.bukkit.enchantments.Enchantment.registerEnchantment(Enchantment.java:241)
[16:39:59 ERROR]: [NovaGuilds]at co.marcin.novaguilds.NovaGuilds.onEnable(NovaGuilds.java:322)
[16:39:59 ERROR]: [NovaGuilds]at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[16:39:59 ERROR]: [NovaGuilds]at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[16:39:59 ERROR]: [NovaGuilds]at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[16:39:59 ERROR]: [NovaGuilds]at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[16:39:59 ERROR]: [NovaGuilds]at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[16:39:59 ERROR]: [NovaGuilds]at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:741)
[16:39:59 ERROR]: [NovaGuilds]at org.bukkit.Bukkit.reload(Bukkit.java:535)
[16:39:59 ERROR]: [NovaGuilds]at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
[16:39:59 ERROR]: [NovaGuilds]at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[16:39:59 ERROR]: [NovaGuilds]at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[16:39:59 ERROR]: [NovaGuilds]at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[16:39:59 ERROR]: [NovaGuilds]at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[16:39:59 ERROR]: [NovaGuilds]at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[16:39:59 ERROR]: [NovaGuilds]at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[16:39:59 ERROR]: [NovaGuilds]at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[16:39:59 ERROR]: [NovaGuilds]at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:39:59 ERROR]: [NovaGuilds]at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:39:59 ERROR]: [NovaGuilds]at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[16:39:59 ERROR]: [NovaGuilds]at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[16:39:59 ERROR]: [NovaGuilds]at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[16:39:59 ERROR]: [NovaGuilds]at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[16:39:59 ERROR]: [NovaGuilds]at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[16:39:59 ERROR]: [NovaGuilds]at java.lang.Thread.run(Thread.java:745)
[16:39:59 ERROR]: [NovaGuilds]
[16:39:59 ERROR]: [NovaGuilds] End of Error.
[16:39:59 ERROR]: [NovaGuilds]`
```
 Enchantment.registerEnchantment(new EnchantmentGlow()); is causing this

**Comment by MarcinWieczorek** [comment]
Please show a full server log.
