### ISSUE TITLE
Error message when running plugin

### ISSUE THREAD

**Issue by ghost** [MarcinWieczorek/NovaGuilds#87]
```[08:06:38 INFO]: [NovaGuilds] Enabling NovaGuilds v40

 Severe error: NullPointerException
  Please send this whole message to the author (/novaguilds)

 Server Information:
  NovaGuilds: #40 (f0d8b68)
  Storage Type: MYSQL
  Bukkit: 1.11.2-R0.1-SNAPSHOT
  Version Implementation: MINECRAFT_1_11_R1
  Java: 1.8.0_131
  Thread: Thread[Server thread,5,main]
  Running CraftBukkit: true

 Exception Message:
  null
   at co.marcin.novaguilds.manager.DependencyManager.setupEconomy(DependencyManager.java:131)
   at co.marcin.novaguilds.NovaGuilds.onEnable(NovaGuilds.java:154)
   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
   at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
   at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376)
   at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326)
   at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419)
   at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380)
   at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335)
   at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272)
   at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542)
   at java.lang.Thread.run(Unknown Source)

 End of Error.
[08:15:10 ERROR]: Error occurred while enabling NovaGuilds v40 (Is it up to date?)
java.lang.NullPointerException
        at co.marcin.novaguilds.manager.MessageManager.getMessagesString(MessageManager.java:174) ~[?:?]
        at co.marcin.novaguilds.manager.MessageManager.sendMessagesMsg(MessageManager.java:246) ~[?:?]
        at co.marcin.novaguilds.impl.basic.MessageWrapperImpl.send(MessageWrapperImpl.java:143) ~[?:?]
        at co.marcin.novaguilds.manager.MessageManager.broadcast(MessageManager.java:308) ~[?:?]
        at co.marcin.novaguilds.manager.MessageManager.broadcast(MessageManager.java:320) ~[?:?]
        at co.marcin.novaguilds.impl.basic.MessageWrapperImpl.broadcast(MessageWrapperImpl.java:180) ~[?:?]
        at co.marcin.novaguilds.util.LoggerUtils.exception(LoggerUtils.java:155) ~[?:?]
        at co.marcin.novaguilds.NovaGuilds.onEnable(NovaGuilds.java:354) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.reload(CraftServer.java:750) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.Bukkit.reload(Bukkit.java:540) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:636) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-6de2fbc-c1aa859]
        at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:437) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-6de2fbc-c1aa859]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-6de2fbc-c1aa859]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-6de2fbc-c1aa859]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-6de2fbc-c1aa859]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]```

**Comment by MarcinWieczorek** [comment]
`Please send this whole message to the author`
I haven't put it there for fun.
NovaGuilds requires a Vault compatible implementation of the economy. You really don't have Essentials?

**Comment by ghost** [comment]
Oh, I am so silly. 
I am sorry to ask you about the NovaGuilds config.yml how to set the pattern to be able to support the Chinese.  I have tried many ways
I am a Taiwanese and English is not very good :)

**Comment by MarcinWieczorek** [comment]
I have no idea, but you can use regular expressions for it. Please share the Taiwanese translation if you have one.

**Comment by ghost** [comment]
No, no, I asked you a question about how NovaGuilds' config should be set up to support Chinese names and tags.  
![test](https://user-images.githubusercontent.com/24543050/28214006-1cfae512-68db-11e7-91f6-f0254e6bf3de.png)

I tried a lot of ways that could not succeed  :(

**Comment by MarcinWieczorek** [comment]
Look I have no idea how to use regex with Chinese characters. I don't understand any of them.
https://stackoverflow.com/questions/9576384/use-regular-expression-to-match-any-chinese-character-in-utf-8-encoding
You need to modify `regexpattern` to suit your needs.

**Comment by ghost** [comment]
Thank you very much.I finally solved the problem.

**Comment by GranTesoro86** [comment]
Right I can not forward this plugin to Taiwan's forum Bahamut it , I just want to forward so that more people know this plugin :)

**Comment by MarcinWieczorek** [comment]
Can you please share the solution? Many Chinese people use my plugin, it might help. Also if you know someone who would translate the plugin to Taiwanese please let me know.

**Comment by ghost** [comment]
Of course !! I'd love to share it.    This is my solution.  
![snipaste_20170719_183353](https://user-images.githubusercontent.com/24543050/28362962-22b83aca-6cb1-11e7-8a2d-a230e776c0f6.png)

or   

``` stringcheck:

  enabled: true

  regex: true

  pattern: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789&"

  regexpattern: "[A-Za-z0-9&|\u4e00-\u9fff§]*"```

**Comment by ghost** [comment]
I have tested Traditional Chinese and Simplified Chinese support.

**Comment by ghost** [comment]
I have translated my own language into Taiwan. I use the NovaGuilds version # 40

This is my language file.     URL:https://pastebin.com/Evk0hJ4Y

There may be some errors, but this is able to support the new version

**Comment by GranTesoro86** [comment]
This is my language file.     URL:https://pastebin.com/Evk0hJ4Y

**Comment by MarcinWieczorek** [comment]
Thank you.
