### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by ghost** [MarcinWieczorek/NovaGuilds#88]
```[20:55:00] [Server thread/ERROR]: [NovaGuilds] 
[20:55:00] [Server thread/ERROR]: [NovaGuilds] Severe error: EventException
[20:55:00] [Server thread/ERROR]: [NovaGuilds]  Please send this whole message to the author (/novaguilds)
[20:55:00] [Server thread/ERROR]: [NovaGuilds] 
[20:55:00] [Server thread/ERROR]: [NovaGuilds] Server Information:
[20:55:00] [Server thread/ERROR]: [NovaGuilds]  NovaGuilds: #39 (0a66e6c)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]  Storage Type: FLAT
[20:55:00] [Server thread/ERROR]: [NovaGuilds]  Bukkit: 1.12-R0.1-SNAPSHOT
[20:55:00] [Server thread/ERROR]: [NovaGuilds]  Version Implementation: MINECRAFT_1_11_R1
[20:55:00] [Server thread/ERROR]: [NovaGuilds]  Java: 1.8.0_131
[20:55:00] [Server thread/ERROR]: [NovaGuilds]  Thread: Thread[Server thread,5,main]
[20:55:00] [Server thread/ERROR]: [NovaGuilds]  Running CraftBukkit: true
[20:55:00] [Server thread/ERROR]: [NovaGuilds] 
[20:55:00] [Server thread/ERROR]: [NovaGuilds] Exception Message: 
[20:55:00] [Server thread/ERROR]: [NovaGuilds]  null
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at co.marcin.novaguilds.impl.util.logging.LoggedPluginManager$2.callEvent(LoggedPluginManager.java:103)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:342)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:162)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at java.lang.Thread.run(Thread.java:748)
[20:55:00] [Server thread/ERROR]: [NovaGuilds] 
[20:55:00] [Server thread/ERROR]: [NovaGuilds] Caused by: java.lang.NullPointerException
[20:55:00] [Server thread/ERROR]: [NovaGuilds]  null
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at co.marcin.novaguilds.NovaGuilds.createTabList(NovaGuilds.java:458)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at co.marcin.novaguilds.NovaGuilds.createTabList(NovaGuilds.java:469)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at co.marcin.novaguilds.listener.LoginListener.onPlayerJoin(LoginListener.java:93)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at java.lang.reflect.Method.invoke(Method.java:498)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at co.marcin.novaguilds.impl.util.logging.LoggedPluginManager$2.callEvent(LoggedPluginManager.java:103)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:342)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:162)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[20:55:00] [Server thread/ERROR]: [NovaGuilds]   at java.lang.Thread.run(Thread.java:748)
[20:55:00] [Server thread/ERROR]: [NovaGuilds] 
[20:55:00] [Server thread/ERROR]: [NovaGuilds] End of Error.
[20:55:00] [Server thread/ERROR]: [NovaGuilds] ```

**Comment by MarcinWieczorek** [comment]
Please reproduce with latest snapshot:
http://novaguilds.pl/
