### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [MarcinWieczorek/NovaGuilds#92]
timings
https://timings.aikar.co/?id=f77004132e534bfe945f6d58e9930967

```
[13:58:33] [Server thread/ERROR]: [NovaGuilds] 
[13:58:33] [Server thread/ERROR]: [NovaGuilds] Severe error: EventException
[13:58:33] [Server thread/ERROR]: [NovaGuilds]  Please send this whole message to the author (/novaguilds)
[13:58:33] [Server thread/ERROR]: [NovaGuilds] 
[13:58:33] [Server thread/ERROR]: [NovaGuilds] Server Information:
[13:58:33] [Server thread/ERROR]: [NovaGuilds]  NovaGuilds: #40 (39222b3)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]  Storage Type: MYSQL
[13:58:33] [Server thread/ERROR]: [NovaGuilds]  Bukkit: 1.12.2-R0.1-SNAPSHOT
[13:58:33] [Server thread/ERROR]: [NovaGuilds]  Version Implementation: MINECRAFT_1_12_R1
[13:58:33] [Server thread/ERROR]: [NovaGuilds]  Java: 1.8.0_151
[13:58:33] [Server thread/ERROR]: [NovaGuilds]  Thread: Thread[Server thread,5,main]
[13:58:33] [Server thread/ERROR]: [NovaGuilds]  Running CraftBukkit: true
[13:58:33] [Server thread/ERROR]: [NovaGuilds] 
[13:58:33] [Server thread/ERROR]: [NovaGuilds] Exception Message: 
[13:58:33] [Server thread/ERROR]: [NovaGuilds]  null
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at co.marcin.novaguilds.impl.util.logging.LoggedPluginManager$2.callEvent(LoggedPluginManager.java:105)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:370)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:183)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.joinGame(SpigotLoginListenerPlay.java:124)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tryJoin(AbstractLoginListenerPlay.java:132)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tick(AbstractLoginListenerPlay.java:94)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.e(SpigotLoginListenerPlay.java:70)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:254)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:940)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at java.lang.Thread.run(Thread.java:748)
[13:58:33] [Server thread/ERROR]: [NovaGuilds] 
[13:58:33] [Server thread/ERROR]: [NovaGuilds] Caused by: java.lang.NullPointerException
[13:58:33] [Server thread/ERROR]: [NovaGuilds]  null
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at co.marcin.novaguilds.NovaGuilds.createTabList(NovaGuilds.java:482)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at co.marcin.novaguilds.NovaGuilds.createTabList(NovaGuilds.java:493)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at co.marcin.novaguilds.listener.LoginListener.onPlayerJoin(LoginListener.java:94)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor312.execute(Unknown Source)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at co.marcin.novaguilds.impl.util.logging.LoggedPluginManager$2.callEvent(LoggedPluginManager.java:105)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:370)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:183)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.joinGame(SpigotLoginListenerPlay.java:124)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tryJoin(AbstractLoginListenerPlay.java:132)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tick(AbstractLoginListenerPlay.java:94)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.e(SpigotLoginListenerPlay.java:70)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:254)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:940)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[13:58:33] [Server thread/ERROR]: [NovaGuilds]   at java.lang.Thread.run(Thread.java:748)
[13:58:34] [Server thread/ERROR]: [NovaGuilds] 
[13:58:34] [Server thread/ERROR]: [NovaGuilds] End of Error.
[13:58:34] [Server thread/ERROR]: [NovaGuilds] 
```

**Comment by MarcinWieczorek** [comment]
Please tell me how to reproduce this issue.

**Comment by KonoromiHimaries** [comment]
nie mam pojęcia, usunąłem plugin.
